project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!data/prep-data.qmd"
  resources:
    - "data/"

website:
  title: "qm-data"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    df-print: paged
    number-sections: true

callout-icon: false

editor: visual

