project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"

website:
  title: "qm-data"
  favicon: assets/img/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    df-print: paged
    number-sections: true

callout-icon: false

editor: visual

